ROLE_SKILLS = {
    "Software Engineer": [
        "Python",
        "Java",
        "C++",
        "Git",
        "GitHub",
        "OOP",
        "SQL",
        "Data Structures",
        "Algorithms",
        "Problem Solving",
    ],

    "AI Engineer": [
        "Python",
        "Artificial Intelligence",
        "Machine Learning",
        "Deep Learning",
        "NLP",
        "LLM",
        "RAG",
        "LangChain",
        "TensorFlow",
        "PyTorch",
        "Pandas",
        "NumPy",
    ],

    "Data Analyst": [
        "Python",
        "SQL",
        "Excel",
        "Power BI",
        "Tableau",
        "Pandas",
        "NumPy",
        "Statistics",
        "Data Visualization",
    ],

    "Web Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node.js",
        "Bootstrap",
        "Git",
        "GitHub",
        "REST API",
    ],

    "Cybersecurity Analyst": [
        "Cybersecurity",
        "Networking",
        "TCP/IP",
        "Linux",
        "Windows",
        "SIEM",
        "Firewalls",
        "Threat Detection",
        "Incident Response",
    ],
}